import { siteUrl } from "@/data/site";

// Branded 1200x630 card generated by src/app/opengraph-image.jsx.
export const defaultOgImage = { url: "/opengraph-image", width: 1200, height: 630, alt: "OrmiTech: AI customer communication platform" };

// Builds page metadata with a self-referencing canonical, Open Graph and Twitter card in one place.
// `path` is the page path ("/pricing"). `absoluteTitle` skips the "| OrmiTech" title template.
export function buildMetadata({ title, description, path, absoluteTitle = false, ogTitle, image = defaultOgImage, type = "website", noindex = false, languages, publishedTime }) {
  const socialTitle = ogTitle || (absoluteTitle ? title : `${title} | OrmiTech`);
  return {
    title: absoluteTitle ? { absolute: title } : title,
    description,
    alternates: { canonical: path, ...(languages ? { languages } : {}) },
    ...(noindex ? { robots: { index: false, follow: true } } : {}),
    openGraph: {
      title: socialTitle,
      description,
      url: path,
      siteName: "OrmiTech",
      type,
      images: [image],
      ...(publishedTime ? { publishedTime } : {})
    },
    twitter: { card: "summary_large_image", title: socialTitle, description, images: [image.url] }
  };
}

export const absoluteUrl = path => `${siteUrl}${path === "/" ? "" : path}`;

export const breadcrumbSchema = items => ({
  "@type": "BreadcrumbList",
  itemListElement: items.map((item, index) => ({ "@type": "ListItem", position: index + 1, name: item.name, item: absoluteUrl(item.path) }))
});

export const faqSchema = items => ({
  "@type": "FAQPage",
  mainEntity: items.map(item => ({ "@type": "Question", name: item.question, acceptedAnswer: { "@type": "Answer", text: item.answer } }))
});

export const webPageSchema = ({ path, name, description, language = "en" }) => ({
  "@type": "WebPage",
  "@id": `${absoluteUrl(path)}#webpage`,
  url: absoluteUrl(path),
  name,
  description,
  inLanguage: language,
  isPartOf: { "@id": `${siteUrl}/#website` },
  about: { "@id": `${siteUrl}/#organization` }
});

// Trims text to a search-result-friendly length at a sentence or word boundary.
export function metaDescription(text, max = 158) {
  if (text.length <= max) return text;
  const sentences = text.match(/[^.!?।]+[.!?।]+/g) || [text];
  let out = "";
  for (const sentence of sentences) {
    if ((out + sentence).trim().length > max) break;
    out += sentence;
  }
  if (out.trim().length >= 70) return out.trim();
  const cut = text.slice(0, max).replace(/\s+\S*$/, "");
  return cut.replace(/[,;:]$/, "") + ".";
}
